[package]
name = "node-spec-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
