[package]
name = "node-spec-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
sha2 = "0.10"
thiserror = { workspace = true }
